In [100]:
import numpy as np
import pandas as pd
from datetime import datetime

# UFC Matches Analysis

### ufc_event_details
    - EVENT, BOUT, DATE, LOCATION

### ufc_fight_results.csv
    - EVENT, BOUT, OUTCOME, WEIGHTCLASS, METHOD, ROUND, TIME FORMAT

### ufc_fight_stats.csv
    BOUT, ROUND, FIGHTER, KD, SIG.STR., SIG.STR.%, TOTAL STR., TD, TD%, SUB.ATT, REV., CTRL, HEAD, BODY, LEG, DISTANCE, CLINCH, GROUND

### ufc_fighter_details.csv
    FIRST, LAST, NICKNAME

### ufc_fighter_tott.csv
    FIGHTER, HEIGHT, WEIGHT, REACH, STANCE, DOB

In [101]:
df_ufc_event_details = pd.read_csv('/home/duyle/Documents/VSC/Project_DAP391/og_dataset/ufc_event_details.csv')
df_ufc_fight_results = pd.read_csv('/home/duyle/Documents/VSC/Project_DAP391/og_dataset/ufc_fight_results.csv')

## Cleaning df_ufc_event_details

In [102]:
df_ufc_event_details = df_ufc_event_details.drop(columns='URL')

In [ ]:
df_ufc_event_details['EVENT'] = df_ufc_event_details['EVENT'].str.strip().str.lower()

df_ufc_event_details['LOCATION'] = df_ufc_event_details['LOCATION'].str.strip().str.lower()

In [108]:
from dateutil import parser
def cv_date(date_str):
    # Automatically parse the date without specifying format
    date_ob = parser.parse(date_str)
    return date_ob.strftime("%m-%d-%y")  # Convert to desired format

# Apply the function to the 'DATE' column
df_ufc_event_details['DATE'] = df_ufc_event_details['DATE'].apply(cv_date)

In [109]:
df_ufc_event_details

,EVENT,DATE,LOCATION
0,ufc fight night: covington vs. buckley,12-14-24,"tampa, florida, usa"
1,ufc 310: pantoja vs. asakura,12-07-24,"las vegas, nevada, usa"
2,ufc fight night: yan vs. figueiredo,11-23-24,"macau, china"
3,ufc 309: jones vs. miocic,11-16-24,"new york city, new york, usa"
4,ufc fight night: magny vs. prates,11-09-24,"las vegas, nevada, usa"
...,...,...,...
710,ufc 6: clash of the titans,07-14-95,"casper, wyoming, usa"
711,ufc 5: the return of the beast,04-07-95,"charlotte, north carolina, usa"
712,ufc 4: revenge of the warriors,12-16-94,"tulsa, oklahoma, usa"
713,ufc 3: the american dream,09-09-94,"charlotte, north carolina, usa"
714,ufc 2: no way out,03-11-94,"denver, colorado, usa"

In [110]:

       
events_to_remove = [
    "ufc - ultimate ultimate '96",
    "ufc 10: the tournament",
    "ufc 9: motor city madness",
    "ufc 8: david vs goliath",
    "ufc - ultimate ultimate '95",
    "ufc 7: the brawl in buffalo",
    "ufc 6: clash of the titans",
    "ufc 5: the return of the beast",
    "ufc 4: revenge of the warriors",
    "ufc 3: the american dream",
    "ufc 2: no way out",
    'ufc - ultimate brazil', 'ufc 17: redemption',
       'ufc 16: battle in the bayou', 'ufc 12: judgement day',
       "ufc - ultimate ultimate '96", 'ufc 11: the proving ground',
]

# Remove rows where 'EVENT' matches the specified values
df_ufc_event_details = df_ufc_event_details[~df_ufc_event_details['EVENT'].isin(events_to_remove)]

In [111]:
df_ufc_event_details

,EVENT,DATE,LOCATION
0,ufc fight night: covington vs. buckley,12-14-24,"tampa, florida, usa"
1,ufc 310: pantoja vs. asakura,12-07-24,"las vegas, nevada, usa"
2,ufc fight night: yan vs. figueiredo,11-23-24,"macau, china"
3,ufc 309: jones vs. miocic,11-16-24,"new york city, new york, usa"
4,ufc fight night: magny vs. prates,11-09-24,"las vegas, nevada, usa"
...,...,...,...
694,ufc 18: the road to the heavyweight title,01-08-99,"new orleans, louisiana, usa"
698,ufc - ultimate japan,12-21-97,"yokohama, kanagawa, japan"
699,ufc 15: collision course,10-17-97,"bay st. louis, mississippi, usa"
700,ufc 14: showdown,07-27-97,"birmingham, alabama, usa"
701,ufc 13: the ultimate force,05-30-97,"augusta, georgia, usa"

In [112]:
df_ufc_event_details.to_csv('ufc_event_details_processed.csv',index=False)

## Cleaning df_ufc_fight_results

In [113]:
df_ufc_fight_results

,EVENT,BOUT,OUTCOME,WEIGHTCLASS,METHOD,ROUND,TIME,TIME FORMAT,REFEREE,DETAILS,URL
0,UFC Fight Night: Covington vs. Buckley,Colby Covington vs. Joaquin Buckley,L/W,Welterweight Bout,TKO - Doctor's Stoppage,3,4:42,5 Rnd (5-5-5-5-5),Dan Miragliotta,Cut above eye,http://ufcstats.com/fight-details/00c6a2ef07ca...
1,UFC Fight Night: Covington vs. Buckley,Cub Swanson vs. Billy Quarantillo,W/L,Featherweight Bout,KO/TKO,3,1:36,3 Rnd (5-5-5),Jason Herzog,Punch to Head At Distance,http://ufcstats.com/fight-details/752101555408...
2,UFC Fight Night: Covington vs. Buckley,Manel Kape vs. Bruno Silva,W/L,Flyweight Bout,KO/TKO,3,1:57,3 Rnd (5-5-5),Keith Peterson,Punches to Head At Distance,http://ufcstats.com/fight-details/1a635a5e4551...
3,UFC Fight Night: Covington vs. Buckley,Vitor Petrino vs. Dustin Jacoby,L/W,Light Heavyweight Bout,KO/TKO,3,3:44,3 Rnd (5-5-5),Andrew Glenn,Punch to Head At Distance,http://ufcstats.com/fight-details/7b1bc4ff776f...
4,UFC Fight Night: Covington vs. Buckley,Adrian Yanez vs. Daniel Marcos,L/W,Bantamweight Bout,Decision - Split,3,5:00,3 Rnd (5-5-5),Keith Peterson,Derek Cleary 27 - 30.Chris Lee 29 - 28.Eric Co...,http://ufcstats.com/fight-details/5238f6470d05...
...,...,...,...,...,...,...,...,...,...,...,...
7930,UFC 2: No Way Out,Orlando Wiet vs. Robert Lucarelli,W/L,Open Weight Bout,KO/TKO,1,2:50,No Time Limit,John McCarthy,toCorner Stoppage,http://ufcstats.com/fight-details/3b020d4914b4...
7931,UFC 2: No Way Out,Frank Hamaker vs. Thaddeus Luster,W/L,Open Weight Bout,Submission,1,4:52,No Time Limit,John McCarthy,Keylock From Half Guard,http://ufcstats.com/fight-details/d917c8c7461b...
7932,UFC 2: No Way Out,Johnny Rhodes vs. David Levicki,W/L,Open Weight Bout,KO/TKO,1,12:13,No Time Limit,John McCarthy,Punches to Head From GuardSubmission to Strikes,http://ufcstats.com/fight-details/ccee020be2e8...
7933,UFC 2: No Way Out,Patrick Smith vs. Ray Wizard,W/L,Open Weight Bout,Submission,1,0:58,No Time Limit,John McCarthy,Guillotine Choke Standing,http://ufcstats.com/fight-details/4b9ae533ccb3...
7934,UFC 2: No Way Out,Scott Morris vs. Sean Daugherty,W/L,Open Weight Bout,Submission,1,0:20,No Time Limit,John McCarthy,Guillotine Choke From Mount,http://ufcstats.com/fight-details/4acab67848e7...

In [114]:
df_ufc_fight_results = df_ufc_fight_results.drop(columns=['URL','DETAILS','REFEREE'])
df_ufc_fight_results['EVENT'] = df_ufc_fight_results['EVENT'].str.strip().str.lower()
df_ufc_fight_results['BOUT'] = df_ufc_fight_results['BOUT'].str.strip().str.lower()
df_ufc_fight_results['METHOD'] = df_ufc_fight_results['METHOD'].str.strip().str.lower()

In [115]:
def cv_time(time):
    minutes,seconds = time.split(':')
    return int(minutes)*60+int(seconds)

In [116]:
df_ufc_fight_results['TIME'] = df_ufc_fight_results['TIME'].apply(cv_time)
df_ufc_fight_results[['FIGHTER_1','FIGHTER_2']] = df_ufc_fight_results['BOUT'].str.split(' vs. ', expand=True)
df_ufc_fight_results['FIGHTER_1'] = df_ufc_fight_results['FIGHTER_1'].str.strip()
df_ufc_fight_results['FIGHTER_2'] = df_ufc_fight_results['FIGHTER_2'].str.strip()

In [117]:
df_ufc_fight_results['TIME FORMAT'].unique()

array(['5 Rnd (5-5-5-5-5)', '3 Rnd (5-5-5)', '3 Rnd + OT (5-5-5-5)',
       '2 Rnd (5-5)', '1 Rnd + 2OT (15-3-3)', '1 Rnd + OT (12-3)',
       '1 Rnd (12)', '1 Rnd + OT (15-3)', '1 Rnd (15)',
       '1 Rnd + 2OT (24-3-3)', '1 Rnd (10)', '1 Rnd + OT (27-3)',
       '1 Rnd (18)', '1 Rnd + OT (30-5)', '1 Rnd + OT (30-3)',
       '1 Rnd (20)', '1 Rnd (30)', '1 Rnd + OT (31-5)', 'No Time Limit'],
      dtype=object)

In [118]:
def cv_time_format(time_fm):
    if 'No Time Limit' in time_fm:
        return None, None, None, None
    rounds_info = time_fm.split(' Rnd')
    round_num = int(rounds_info[0])

    if '+' in rounds_info[1]:
        main, overtime = rounds_info[1].split('OT')
        main_round_time = overtime.strip(' ( )').split('-')[0]
        ot_round_time = overtime.strip(' ()').split('-')[1]
        num_ot_rounds = main.split(' ')[2].strip()
        return round_num, main_round_time, num_ot_rounds, ot_round_time
    else:
        main_round_time = rounds_info[1].strip(' ( )').split('-')[0]

        return round_num, main_round_time, 0, 0
df_ufc_fight_results[['Total_Rounds_Format', 'Main_round_time_Format', 'Num_overtime_rounds_Format', 'Overtime_round_time_Format']] = df_ufc_fight_results['TIME FORMAT'].apply(cv_time_format).apply(pd.Series)

In [120]:
df_ufc_fight_results

,EVENT,BOUT,OUTCOME,WEIGHTCLASS,METHOD,ROUND,TIME,TIME FORMAT,FIGHTER_1,FIGHTER_2,Total_Rounds_Format,Main_round_time_Format,Num_overtime_rounds_Format,Overtime_round_time_Format
0,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,L/W,Welterweight Bout,tko - doctor's stoppage,3,282,5 Rnd (5-5-5-5-5),colby covington,joaquin buckley,5.0,5,0,0
1,ufc fight night: covington vs. buckley,cub swanson vs. billy quarantillo,W/L,Featherweight Bout,ko/tko,3,96,3 Rnd (5-5-5),cub swanson,billy quarantillo,3.0,5,0,0
2,ufc fight night: covington vs. buckley,manel kape vs. bruno silva,W/L,Flyweight Bout,ko/tko,3,117,3 Rnd (5-5-5),manel kape,bruno silva,3.0,5,0,0
3,ufc fight night: covington vs. buckley,vitor petrino vs. dustin jacoby,L/W,Light Heavyweight Bout,ko/tko,3,224,3 Rnd (5-5-5),vitor petrino,dustin jacoby,3.0,5,0,0
4,ufc fight night: covington vs. buckley,adrian yanez vs. daniel marcos,L/W,Bantamweight Bout,decision - split,3,300,3 Rnd (5-5-5),adrian yanez,daniel marcos,3.0,5,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7930,ufc 2: no way out,orlando wiet vs. robert lucarelli,W/L,Open Weight Bout,ko/tko,1,170,No Time Limit,orlando wiet,robert lucarelli,NaN,None,None,None
7931,ufc 2: no way out,frank hamaker vs. thaddeus luster,W/L,Open Weight Bout,submission,1,292,No Time Limit,frank hamaker,thaddeus luster,NaN,None,None,None
7932,ufc 2: no way out,johnny rhodes vs. david levicki,W/L,Open Weight Bout,ko/tko,1,733,No Time Limit,johnny rhodes,david levicki,NaN,None,None,None
7933,ufc 2: no way out,patrick smith vs. ray wizard,W/L,Open Weight Bout,submission,1,58,No Time Limit,patrick smith,ray wizard,NaN,None,None,None
7934,ufc 2: no way out,scott morris vs. sean daugherty,W/L,Open Weight Bout,submission,1,20,No Time Limit,scott morris,sean daugherty,NaN,None,None,None

In [121]:
df_ufc_fight_results['METHOD'].unique()

array(["tko - doctor's stoppage", 'ko/tko', 'decision - split',
       'decision - unanimous', 'submission', 'could not continue',
       'decision - majority', 'dq', 'overturned', 'other'], dtype=object)

In [122]:
df_ufc_fight_results['WEIGHTCLASS'].unique()

array(['Welterweight Bout', 'Featherweight Bout', 'Flyweight Bout',
       'Light Heavyweight Bout', 'Bantamweight Bout', 'Lightweight Bout',
       "Women's Flyweight Bout", "Women's Strawweight Bout",
       'UFC Flyweight Title Bout', 'Heavyweight Bout',
       'Catch Weight Bout', 'UFC Heavyweight Title Bout',
       'Middleweight Bout', "Women's Bantamweight Bout",
       'UFC Light Heavyweight Title Bout',
       "UFC Women's Bantamweight Title Bout",
       'UFC Bantamweight Title Bout', "UFC Women's Flyweight Title Bout",
       'UFC Middleweight Title Bout', 'UFC Welterweight Title Bout',
       'UFC Interim Heavyweight Title Bout', 'UFC Lightweight Title Bout',
       "UFC Women's Strawweight Title Bout",
       'UFC Featherweight Title Bout', "Women's Featherweight Bout",
       'UFC Interim Featherweight Title Bout',
       'UFC Interim Flyweight Title Bout',
       'UFC Interim Bantamweight Title Bout',
       "UFC Women's Featherweight Title Bout",
       'UFC Interim Lightweight Title Bout',
       'UFC Interim Middleweight Title Bout',
       'Ultimate Fighter 28 Heavyweight Tournament Title Bout',
       "Ultimate Fighter 28 Women's Featherweight Tournament Title Bout",
       'Ultimate Fighter 27 Lightweight Tournament Title Bout',
       'Ultimate Fighter 27 Featherweight Tournament Title Bout',
       'UFC Interim Welterweight Title Bout',
       'Ultimate Fighter 25 Welterweight Tournament Title Bout',
       'Ultimate Fighter Latin America 3 Lightweight Tournament Title Bout',
       'Ultimate Fighter 23 Light Heavyweight Tournament Title Bout',
       "Ultimate Fighter 23 Women's Strawweight Tournament Title Bout",
       'UFC Interim Light Heavyweight Title Bout',
       'Ultimate Fighter 22 Lightweight Tournament Title Bout',
       'Ultimate Fighter Latin America 2 Welterweight Tournament Title Bout',
       'Ultimate Fighter Latin America 2 Lightweight Tournament Title Bout',
       'Ultimate Fighter Brazil 4 Lightweight Tournament Title Bout',
       'Ultimate Fighter Brazil 4 Bantamweight Tournament Title Bout',
       'Ultimate Fighter 21 Welterweight Tournament Title Bout',
       'Ultimate Fighter Latin America Featherweight Tournament Title Bout',
       'Ultimate Fighter Latin America Bantamweight Tournament Title Bout',
       'Ultimate Fighter China Featherweight Tournament Title Bout',
       'Ultimate Fighter 19 Light Heavyweight Tournament Title Bout',
       'Ultimate Fighter 19 Middleweight Tournament Title Bout',
       'Ultimate Fighter Brazil 3 Heavyweight Tournament Title Bout',
       'Ultimate Fighter Brazil 3 Middleweight Tournament Title Bout',
       'TUF Nations Canada vs. Australia Middleweight Tournament Title Bout',
       'TUF Nations Canada vs. Australia Welterweight Tournament Title Bout',
       'Ultimate Fighter China Welterweight Tournament Title Bout',
       "Ultimate Fighter 18 Women's Bantamweight Tournament Title Bout",
       'Ultimate Fighter 18 Bantamweight Tournament Title Bout',
       'Ultimate Fighter Brazil 2 Welterweight Tournament Title Bout',
       'Ultimate Fighter 17 Middleweight Tournament Title Bout',
       'Ultimate Fighter 16 Welterweight Tournament Title Bout',
       'Ultimate Fighter Australia vs. UK Welterweight Tournament Title Bout',
       'Ultimate Fighter Australia vs. UK Lightweight Tournament Title Bout',
       'Ultimate Fighter Brazil 1 Middleweight Tournament Title Bout',
       'Ultimate Fighter Brazil 1 Featherweight Tournament Title Bout',
       'Ultimate Fighter 15 Lightweight Tournament Title Bout',
       'Ultimate Fighter 14 Featherweight Tournament Title Bout',
       'Ultimate Fighter 14 Bantamweight Tournament Title Bout',
       'Ultimate Fighter 13 Welterweight Tournament Title Bout',
       'Ultimate Fighter 12 Lightweight Tournament Title Bout',
       'Ultimate Fighter 11 Middleweight Tournament Title Bout',
       'Ultimate Fighter 10 Heavyweight Tournament Title Bout',
       'Ultimate Fighter 9 Welterweight Tournament Title Bout',
       'Ultimate Fighter 9 Lightweight Tournament Title Bout',
       'Ultimate Fighter 8 Lightweight Tournament Title Bout',
       'Ultimate Fighter 8 Light Heavyweight Tournament Title Bout',
       'Ultimate Fighter 7 Middleweight Tournament Title Bout',
       'Ultimate Fighter 6 Welterweight Tournament Title Bout',
       'Ultimate Fighter 5 Lightweight Tournament Title Bout',
       'Ultimate Fighter 4 Welterweight Tournament Title Bout',
       'Ultimate Fighter 4 Middleweight Tournament Title Bout',
       'Ultimate Fighter 3 Light Heavyweight Tournament Title Bout',
       'Ultimate Fighter 3 Middleweight Tournament Title Bout',
       'Ultimate Fighter 2 Heavyweight Tournament Title Bout',
       'Ultimate Fighter 2 Welterweight Tournament Title Bout',
       'Ultimate Fighter 1 Light Heavyweight Tournament Title Bout',
       'Ultimate Fighter 1 Middleweight Tournament Title Bout',
       'Super Heavyweight Bout',
       'Ultimate Japan 2 Heavyweight Tournament Title Bout',
       'Open Weight Bout', 'UFC 17 Middleweight Tournament Title Bout',
       'Ultimate Japan Heavyweight Tournament Title Bout',
       'UFC 15 Heavyweight Tournament Title Bout',
       'UFC 14 Heavyweight Tournament Title Bout',
       'UFC 14 Middleweight Tournament Title Bout',
       'UFC 13 Heavyweight Tournament Title Bout',
       'UFC 13 Lightweight Tournament Title Bout',
       "Ultimate Ultimate '96 Tournament Title Bout",
       'UFC 10 Tournament Title Bout', 'UFC Superfight Championship Bout',
       'UFC 8 Tournament Title Bout',
       "Ultimate Ultimate '95 Tournament Title Bout",
       'UFC 7 Tournament Title Bout', 'UFC 6 Tournament Title Bout',
       'UFC 5 Tournament Title Bout', 'UFC 4 Tournament Title Bout',
       'UFC 3 Tournament Title Bout', 'UFC 2 Tournament Title Bout'],
      dtype=object)

In [123]:
df_ufc_fight_results['gender'] = df_ufc_fight_results['WEIGHTCLASS'].apply(lambda x: 1 if 'Women' in x else 0)
df_ufc_fight_results['is_title_bout'] = df_ufc_fight_results['WEIGHTCLASS'].apply(lambda x: 1 if 'Title' in x else 0)

In [124]:
weight_class_list = [
    'Lightweight', 'Strawweight', 'Featherweight', 'Flyweight', 'Bantamweight', 
    'Welterweight', 'Middleweight', 'Light Heavyweight', 'Heavyweight', 
    'Super Heavyweight', 'Catch Weight', 'Open Weight'
]
def cv_weight_class(weight_class):
    for wc in weight_class_list:
        if wc in weight_class:
            return wc
    return None

df_ufc_fight_results['weight_class'] = df_ufc_fight_results['WEIGHTCLASS'].apply(cv_weight_class)

In [125]:
check = df_ufc_fight_results[df_ufc_fight_results['weight_class'].isna()]
check['EVENT']

7821       ufc - ultimate ultimate '96
7839            ufc 10: the tournament
7848         ufc 9: motor city madness
7855           ufc 8: david vs goliath
7856           ufc 8: david vs goliath
7864       ufc - ultimate ultimate '95
7873       ufc 7: the brawl in buffalo
7874       ufc 7: the brawl in buffalo
7884        ufc 6: clash of the titans
7885        ufc 6: clash of the titans
7894    ufc 5: the return of the beast
7895    ufc 5: the return of the beast
7904    ufc 4: revenge of the warriors
7914         ufc 3: the american dream
7920                 ufc 2: no way out
Name: EVENT, dtype: object

In [126]:
events_to_remove = [
    "ufc - ultimate ultimate '96",
    "ufc 10: the tournament",
    "ufc 9: motor city madness",
    "ufc 8: david vs goliath",
    "ufc - ultimate ultimate '95",
    "ufc 7: the brawl in buffalo",
    "ufc 6: clash of the titans",
    "ufc 5: the return of the beast",
    "ufc 4: revenge of the warriors",
    "ufc 3: the american dream",
    "ufc 2: no way out",
    'ufc - ultimate brazil', 'ufc 17: redemption',
       'ufc 16: battle in the bayou', 'ufc 12: judgement day',
       "ufc - ultimate ultimate '96", 'ufc 11: the proving ground',
]

# Remove rows where 'EVENT' matches the specified values
df_ufc_fight_results =df_ufc_fight_results[~df_ufc_fight_results['EVENT'].isin(events_to_remove)]

In [127]:
df_ufc_fight_results

,EVENT,BOUT,OUTCOME,WEIGHTCLASS,METHOD,ROUND,TIME,TIME FORMAT,FIGHTER_1,FIGHTER_2,Total_Rounds_Format,Main_round_time_Format,Num_overtime_rounds_Format,Overtime_round_time_Format,gender,is_title_bout,weight_class
0,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,L/W,Welterweight Bout,tko - doctor's stoppage,3,282,5 Rnd (5-5-5-5-5),colby covington,joaquin buckley,5.0,5,0,0,0,0,Welterweight
1,ufc fight night: covington vs. buckley,cub swanson vs. billy quarantillo,W/L,Featherweight Bout,ko/tko,3,96,3 Rnd (5-5-5),cub swanson,billy quarantillo,3.0,5,0,0,0,0,Featherweight
2,ufc fight night: covington vs. buckley,manel kape vs. bruno silva,W/L,Flyweight Bout,ko/tko,3,117,3 Rnd (5-5-5),manel kape,bruno silva,3.0,5,0,0,0,0,Flyweight
3,ufc fight night: covington vs. buckley,vitor petrino vs. dustin jacoby,L/W,Light Heavyweight Bout,ko/tko,3,224,3 Rnd (5-5-5),vitor petrino,dustin jacoby,3.0,5,0,0,0,0,Light Heavyweight
4,ufc fight night: covington vs. buckley,adrian yanez vs. daniel marcos,L/W,Bantamweight Bout,decision - split,3,300,3 Rnd (5-5-5),adrian yanez,daniel marcos,3.0,5,0,0,0,0,Bantamweight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7807,ufc 13: the ultimate force,steven graham vs. dmitri stepanov,W/L,Heavyweight Bout,submission,1,90,1 Rnd + OT (12-3),steven graham,dmitri stepanov,1.0,12,,3,0,0,Heavyweight
7808,ufc 13: the ultimate force,enson inoue vs. royce alger,W/L,Lightweight Bout,submission,1,96,1 Rnd + OT (12-3),enson inoue,royce alger,1.0,12,,3,0,0,Lightweight
7809,ufc 13: the ultimate force,guy mezger vs. christophe leninger,W/L,Lightweight Bout,decision - unanimous,2,180,1 Rnd + OT (12-3),guy mezger,christophe leninger,1.0,12,,3,0,0,Lightweight
7810,ufc 13: the ultimate force,jack nilson vs. saeed hosseini,W/L,Lightweight Bout,ko/tko,1,83,1 Rnd + OT (12-3),jack nilson,saeed hosseini,1.0,12,,3,0,0,Lightweight
7811,ufc 13: the ultimate force,tito ortiz vs. wes albritton,W/L,Lightweight Bout,ko/tko,1,31,1 Rnd + OT (12-3),tito ortiz,wes albritton,1.0,12,,3,0,0,Lightweight

In [128]:
df_ufc_fight_results

,EVENT,BOUT,OUTCOME,WEIGHTCLASS,METHOD,ROUND,TIME,TIME FORMAT,FIGHTER_1,FIGHTER_2,Total_Rounds_Format,Main_round_time_Format,Num_overtime_rounds_Format,Overtime_round_time_Format,gender,is_title_bout,weight_class
0,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,L/W,Welterweight Bout,tko - doctor's stoppage,3,282,5 Rnd (5-5-5-5-5),colby covington,joaquin buckley,5.0,5,0,0,0,0,Welterweight
1,ufc fight night: covington vs. buckley,cub swanson vs. billy quarantillo,W/L,Featherweight Bout,ko/tko,3,96,3 Rnd (5-5-5),cub swanson,billy quarantillo,3.0,5,0,0,0,0,Featherweight
2,ufc fight night: covington vs. buckley,manel kape vs. bruno silva,W/L,Flyweight Bout,ko/tko,3,117,3 Rnd (5-5-5),manel kape,bruno silva,3.0,5,0,0,0,0,Flyweight
3,ufc fight night: covington vs. buckley,vitor petrino vs. dustin jacoby,L/W,Light Heavyweight Bout,ko/tko,3,224,3 Rnd (5-5-5),vitor petrino,dustin jacoby,3.0,5,0,0,0,0,Light Heavyweight
4,ufc fight night: covington vs. buckley,adrian yanez vs. daniel marcos,L/W,Bantamweight Bout,decision - split,3,300,3 Rnd (5-5-5),adrian yanez,daniel marcos,3.0,5,0,0,0,0,Bantamweight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7807,ufc 13: the ultimate force,steven graham vs. dmitri stepanov,W/L,Heavyweight Bout,submission,1,90,1 Rnd + OT (12-3),steven graham,dmitri stepanov,1.0,12,,3,0,0,Heavyweight
7808,ufc 13: the ultimate force,enson inoue vs. royce alger,W/L,Lightweight Bout,submission,1,96,1 Rnd + OT (12-3),enson inoue,royce alger,1.0,12,,3,0,0,Lightweight
7809,ufc 13: the ultimate force,guy mezger vs. christophe leninger,W/L,Lightweight Bout,decision - unanimous,2,180,1 Rnd + OT (12-3),guy mezger,christophe leninger,1.0,12,,3,0,0,Lightweight
7810,ufc 13: the ultimate force,jack nilson vs. saeed hosseini,W/L,Lightweight Bout,ko/tko,1,83,1 Rnd + OT (12-3),jack nilson,saeed hosseini,1.0,12,,3,0,0,Lightweight
7811,ufc 13: the ultimate force,tito ortiz vs. wes albritton,W/L,Lightweight Bout,ko/tko,1,31,1 Rnd + OT (12-3),tito ortiz,wes albritton,1.0,12,,3,0,0,Lightweight

In [129]:
df_ufc_fight_results.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7787 entries, 0 to 7811
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   EVENT                       7787 non-null   object
 1   BOUT                        7787 non-null   object
 2   OUTCOME                     7787 non-null   object
 3   WEIGHTCLASS                 7787 non-null   object
 4   METHOD                      7787 non-null   object
 5   ROUND                       7787 non-null   int64
 6   TIME                        7787 non-null   int64
 7   TIME FORMAT                 7787 non-null   object
 8   FIGHTER_1                   7787 non-null   object
 9   FIGHTER_2                   7787 non-null   object
 10  Total_Rounds_Format         7787 non-null   float64
 11  Main_round_time_Format      7787 non-null   object
 12  Num_overtime_rounds_Format  7787 non-null   object
 13  Overtime_round_time_Format  7787 non-null   object
 14  gender                      7787 non-null   int64
 15  is_title_bout               7787 non-null   int64
 16  weight_class                7787 non-null   object
dtypes: float64(1), int64(4), object(12)
memory usage: 1.1+ MB

#### Drop all the superfight championship since there was no weightclass being introduced back in the day these matches took place

In [130]:
df_ufc_fight_results['weight_class'] = df_ufc_fight_results['weight_class'].str.strip().str.lower()
df_ufc_fight_results = df_ufc_fight_results.drop(columns='WEIGHTCLASS')

/tmp/ipykernel_255208/2838625494.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ufc_fight_results['weight_class'] = df_ufc_fight_results['weight_class'].str.strip().str.lower()

In [131]:
df_ufc_fight_results[['fighter_1_result', 'fighter_2_result']] = df_ufc_fight_results['OUTCOME'].str.split('/', expand=True)

In [ ]:
df_ufc_fight_results['fighter_1_result'].unique()

array(['L', 'W', 'NC', 'D'], dtype=object)

In [ ]:
def calculate_records(group, result_column):
    return pd.Series({
        'wins': (group[result_column] == 'W').sum(),
        'losses': (group[result_column] == 'L').sum(),
        'draws': (group[result_column] == 'D').sum(),
        'nc': (group[result_column] == 'NC').sum()
    })

records = []
for fighter_col, result_col in [('FIGHTER_1', 'fighter_1_result'), ('FIGHTER_2', 'fighter_2_result')]:
    records.append(
        df_ufc_fight_results.groupby(fighter_col)
        .apply(calculate_records, result_column=result_col)
        .reset_index()
        .rename(columns={fighter_col: 'Fighter'})
    )

final_fighter_records = (
    pd.concat(records)
    .groupby('Fighter', as_index=False)
    .sum()
)

/tmp/ipykernel_255208/19958598.py:13: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calculate_records, result_column=result_col)
/tmp/ipykernel_255208/19958598.py:13: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calculate_records, result_column=result_col)

In [ ]:
final_fighter_records['total_matches'] = final_fighter_records[['wins', 'losses', 'draws', 'nc']].sum(axis=1)

In [ ]:
final_fighter_records.to_csv('summary.csv',index=False)

In [132]:
df_ufc_fight_results

,EVENT,BOUT,OUTCOME,METHOD,ROUND,TIME,TIME FORMAT,FIGHTER_1,FIGHTER_2,Total_Rounds_Format,Main_round_time_Format,Num_overtime_rounds_Format,Overtime_round_time_Format,gender,is_title_bout,weight_class,fighter_1_result,fighter_2_result
0,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,L/W,tko - doctor's stoppage,3,282,5 Rnd (5-5-5-5-5),colby covington,joaquin buckley,5.0,5,0,0,0,0,welterweight,L,W
1,ufc fight night: covington vs. buckley,cub swanson vs. billy quarantillo,W/L,ko/tko,3,96,3 Rnd (5-5-5),cub swanson,billy quarantillo,3.0,5,0,0,0,0,featherweight,W,L
2,ufc fight night: covington vs. buckley,manel kape vs. bruno silva,W/L,ko/tko,3,117,3 Rnd (5-5-5),manel kape,bruno silva,3.0,5,0,0,0,0,flyweight,W,L
3,ufc fight night: covington vs. buckley,vitor petrino vs. dustin jacoby,L/W,ko/tko,3,224,3 Rnd (5-5-5),vitor petrino,dustin jacoby,3.0,5,0,0,0,0,light heavyweight,L,W
4,ufc fight night: covington vs. buckley,adrian yanez vs. daniel marcos,L/W,decision - split,3,300,3 Rnd (5-5-5),adrian yanez,daniel marcos,3.0,5,0,0,0,0,bantamweight,L,W
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7807,ufc 13: the ultimate force,steven graham vs. dmitri stepanov,W/L,submission,1,90,1 Rnd + OT (12-3),steven graham,dmitri stepanov,1.0,12,,3,0,0,heavyweight,W,L
7808,ufc 13: the ultimate force,enson inoue vs. royce alger,W/L,submission,1,96,1 Rnd + OT (12-3),enson inoue,royce alger,1.0,12,,3,0,0,lightweight,W,L
7809,ufc 13: the ultimate force,guy mezger vs. christophe leninger,W/L,decision - unanimous,2,180,1 Rnd + OT (12-3),guy mezger,christophe leninger,1.0,12,,3,0,0,lightweight,W,L
7810,ufc 13: the ultimate force,jack nilson vs. saeed hosseini,W/L,ko/tko,1,83,1 Rnd + OT (12-3),jack nilson,saeed hosseini,1.0,12,,3,0,0,lightweight,W,L
7811,ufc 13: the ultimate force,tito ortiz vs. wes albritton,W/L,ko/tko,1,31,1 Rnd + OT (12-3),tito ortiz,wes albritton,1.0,12,,3,0,0,lightweight,W,L

In [133]:
df_ufc_fight_results.isnull().sum()

EVENT                         0
BOUT                          0
OUTCOME                       0
METHOD                        0
ROUND                         0
TIME                          0
TIME FORMAT                   0
FIGHTER_1                     0
FIGHTER_2                     0
Total_Rounds_Format           0
Main_round_time_Format        0
Num_overtime_rounds_Format    0
Overtime_round_time_Format    0
gender                        0
is_title_bout                 0
weight_class                  0
fighter_1_result              0
fighter_2_result              0
dtype: int64

In [134]:
df_ufc_fight_results.to_csv('ufc_fight_results_processed.csv',index=False)