In [1]:
import numpy as np
import pandas as pd
from datetime import datetime

In [131]:
df_event_details_og = pd.read_csv('/home/duyle/Documents/VSC/Project_DAP391/og_dataset/ufc_event_details.csv')
df_results_og= pd.read_csv('/home/duyle/Documents/VSC/Project_DAP391/og_dataset/ufc_fight_results.csv')
df_stats_og= pd.read_csv('/home/duyle/Documents/VSC/Project_DAP391/og_dataset/ufc_fight_stats.csv')
df_ufc_fighter_tott = pd.read_csv('/home/duyle/Documents/VSC/Project_DAP391/og_dataset/ufc_fighter_tott.csv')

In [132]:
df_ufc_fighter_tott.head()

,FIGHTER,HEIGHT,WEIGHT,REACH,STANCE,DOB,URL
0,Tom Aaron,--,155 lbs.,--,NaN,"Jul 13, 1978",http://ufcstats.com/fighter-details/93fe7332d1...
1,Danny Abbadi,"5' 11""",155 lbs.,--,Orthodox,"Jul 03, 1983",http://ufcstats.com/fighter-details/15df64c02b...
2,David Abbott,"6' 0""",265 lbs.,--,Switch,--,http://ufcstats.com/fighter-details/b361180739...
3,Shamil Abdurakhimov,"6' 3""",235 lbs.,"76""",Orthodox,"Sep 02, 1981",http://ufcstats.com/fighter-details/2f5cbecbbe...
4,Hiroyuki Abe,"5' 6""",145 lbs.,--,Orthodox,--,http://ufcstats.com/fighter-details/c0ed7b2081...

In [133]:
df_event_details_og.head()

,EVENT,URL,DATE,LOCATION
0,UFC Fight Night: Covington vs. Buckley,http://ufcstats.com/event-details/72c9c2eadfc3...,"December 14, 2024","Tampa, Florida, USA"
1,UFC 310: Pantoja vs. Asakura,http://ufcstats.com/event-details/ad23903ef3af...,"December 07, 2024","Las Vegas, Nevada, USA"
2,UFC Fight Night: Yan vs. Figueiredo,http://ufcstats.com/event-details/e955046551f8...,"November 23, 2024","Macau, China"
3,UFC 309: Jones vs. Miocic,http://ufcstats.com/event-details/daff32bc96d1...,"November 16, 2024","New York City, New York, USA"
4,UFC Fight Night: Magny vs. Prates,http://ufcstats.com/event-details/585f9ffdb0cd...,"November 09, 2024","Las Vegas, Nevada, USA"

In [134]:
df_results_og.head()

,EVENT,BOUT,OUTCOME,WEIGHTCLASS,METHOD,ROUND,TIME,TIME FORMAT,REFEREE,DETAILS,URL
0,UFC Fight Night: Covington vs. Buckley,Colby Covington vs. Joaquin Buckley,L/W,Welterweight Bout,TKO - Doctor's Stoppage,3,4:42,5 Rnd (5-5-5-5-5),Dan Miragliotta,Cut above eye,http://ufcstats.com/fight-details/00c6a2ef07ca...
1,UFC Fight Night: Covington vs. Buckley,Cub Swanson vs. Billy Quarantillo,W/L,Featherweight Bout,KO/TKO,3,1:36,3 Rnd (5-5-5),Jason Herzog,Punch to Head At Distance,http://ufcstats.com/fight-details/752101555408...
2,UFC Fight Night: Covington vs. Buckley,Manel Kape vs. Bruno Silva,W/L,Flyweight Bout,KO/TKO,3,1:57,3 Rnd (5-5-5),Keith Peterson,Punches to Head At Distance,http://ufcstats.com/fight-details/1a635a5e4551...
3,UFC Fight Night: Covington vs. Buckley,Vitor Petrino vs. Dustin Jacoby,L/W,Light Heavyweight Bout,KO/TKO,3,3:44,3 Rnd (5-5-5),Andrew Glenn,Punch to Head At Distance,http://ufcstats.com/fight-details/7b1bc4ff776f...
4,UFC Fight Night: Covington vs. Buckley,Adrian Yanez vs. Daniel Marcos,L/W,Bantamweight Bout,Decision - Split,3,5:00,3 Rnd (5-5-5),Keith Peterson,Derek Cleary 27 - 30.Chris Lee 29 - 28.Eric Co...,http://ufcstats.com/fight-details/5238f6470d05...

In [135]:
df_stats_og.head()

,EVENT,BOUT,ROUND,FIGHTER,KD,SIG.STR.,SIG.STR. %,TOTAL STR.,TD,TD %,SUB.ATT,REV.,CTRL,HEAD,BODY,LEG,DISTANCE,CLINCH,GROUND
0,UFC Fight Night: Covington vs. Buckley,Colby Covington vs. Joaquin Buckley,Round 1,Colby Covington,0.0,10 of 51,19%,10 of 51,0 of 2,0%,0.0,0.0,0:22,5 of 42,4 of 6,1 of 3,10 of 51,0 of 0,0 of 0
1,UFC Fight Night: Covington vs. Buckley,Colby Covington vs. Joaquin Buckley,Round 2,Colby Covington,0.0,19 of 50,38%,25 of 56,1 of 3,33%,0.0,0.0,1:28,13 of 43,4 of 5,2 of 2,17 of 48,0 of 0,2 of 2
2,UFC Fight Night: Covington vs. Buckley,Colby Covington vs. Joaquin Buckley,Round 3,Colby Covington,0.0,8 of 23,34%,36 of 54,0 of 3,0%,0.0,0.0,1:50,8 of 23,0 of 0,0 of 0,6 of 21,0 of 0,2 of 2
3,UFC Fight Night: Covington vs. Buckley,Colby Covington vs. Joaquin Buckley,Round 1,Joaquin Buckley,0.0,23 of 55,41%,23 of 55,0 of 0,---,0.0,0.0,0:09,18 of 47,4 of 7,1 of 1,20 of 49,1 of 2,2 of 4
4,UFC Fight Night: Covington vs. Buckley,Colby Covington vs. Joaquin Buckley,Round 2,Joaquin Buckley,0.0,28 of 55,50%,29 of 56,0 of 1,0%,0.0,0.0,0:01,20 of 46,6 of 7,2 of 2,24 of 50,4 of 5,0 of 0

In [4]:
df_results = pd.read_csv('/home/duyle/Documents/VSC/Project_DAP391/ufc_fight_results_processed.csv')
df_stats = pd.read_csv('fight_stats_with_weghtclass_date_location.csv')
df_fighters = pd.read_csv('fighters.csv')

In [137]:
df_results

,EVENT,BOUT,METHOD,ROUND,TIME,FIGHTER_1,FIGHTER_2,Total_Rounds_Format,Main_round_time_Format,Num_overtime_rounds_Format,Overtime_round_time_Format,gender,is_title_bout,weight_class,fighter_1_result,fighter_2_result
0,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,tko - doctor's stoppage,3,282,colby covington,joaquin buckley,5.0,5.0,0.0,0.0,0,0,welterweight,L,W
1,ufc fight night: covington vs. buckley,cub swanson vs. billy quarantillo,ko/tko,3,96,cub swanson,billy quarantillo,3.0,5.0,0.0,0.0,0,0,featherweight,W,L
2,ufc fight night: covington vs. buckley,manel kape vs. bruno silva,ko/tko,3,117,manel kape,bruno silva,3.0,5.0,0.0,0.0,0,0,flyweight,W,L
3,ufc fight night: covington vs. buckley,vitor petrino vs. dustin jacoby,ko/tko,3,224,vitor petrino,dustin jacoby,3.0,5.0,0.0,0.0,0,0,light heavyweight,L,W
4,ufc fight night: covington vs. buckley,adrian yanez vs. daniel marcos,decision - split,3,300,adrian yanez,daniel marcos,3.0,5.0,0.0,0.0,0,0,bantamweight,L,W
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7925,ufc 2: no way out,orlando wiet vs. robert lucarelli,ko/tko,1,170,orlando wiet,robert lucarelli,NaN,NaN,NaN,NaN,0,0,open weight,W,L
7926,ufc 2: no way out,frank hamaker vs. thaddeus luster,submission,1,292,frank hamaker,thaddeus luster,NaN,NaN,NaN,NaN,0,0,open weight,W,L
7927,ufc 2: no way out,johnny rhodes vs. david levicki,ko/tko,1,733,johnny rhodes,david levicki,NaN,NaN,NaN,NaN,0,0,open weight,W,L
7928,ufc 2: no way out,patrick smith vs. ray wizard,submission,1,58,patrick smith,ray wizard,NaN,NaN,NaN,NaN,0,0,open weight,W,L
7929,ufc 2: no way out,scott morris vs. sean daugherty,submission,1,20,scott morris,sean daugherty,NaN,NaN,NaN,NaN,0,0,open weight,W,L

In [138]:
df_results

,EVENT,BOUT,METHOD,ROUND,TIME,FIGHTER_1,FIGHTER_2,Total_Rounds_Format,Main_round_time_Format,Num_overtime_rounds_Format,Overtime_round_time_Format,gender,is_title_bout,weight_class,fighter_1_result,fighter_2_result
0,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,tko - doctor's stoppage,3,282,colby covington,joaquin buckley,5.0,5.0,0.0,0.0,0,0,welterweight,L,W
1,ufc fight night: covington vs. buckley,cub swanson vs. billy quarantillo,ko/tko,3,96,cub swanson,billy quarantillo,3.0,5.0,0.0,0.0,0,0,featherweight,W,L
2,ufc fight night: covington vs. buckley,manel kape vs. bruno silva,ko/tko,3,117,manel kape,bruno silva,3.0,5.0,0.0,0.0,0,0,flyweight,W,L
3,ufc fight night: covington vs. buckley,vitor petrino vs. dustin jacoby,ko/tko,3,224,vitor petrino,dustin jacoby,3.0,5.0,0.0,0.0,0,0,light heavyweight,L,W
4,ufc fight night: covington vs. buckley,adrian yanez vs. daniel marcos,decision - split,3,300,adrian yanez,daniel marcos,3.0,5.0,0.0,0.0,0,0,bantamweight,L,W
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7925,ufc 2: no way out,orlando wiet vs. robert lucarelli,ko/tko,1,170,orlando wiet,robert lucarelli,NaN,NaN,NaN,NaN,0,0,open weight,W,L
7926,ufc 2: no way out,frank hamaker vs. thaddeus luster,submission,1,292,frank hamaker,thaddeus luster,NaN,NaN,NaN,NaN,0,0,open weight,W,L
7927,ufc 2: no way out,johnny rhodes vs. david levicki,ko/tko,1,733,johnny rhodes,david levicki,NaN,NaN,NaN,NaN,0,0,open weight,W,L
7928,ufc 2: no way out,patrick smith vs. ray wizard,submission,1,58,patrick smith,ray wizard,NaN,NaN,NaN,NaN,0,0,open weight,W,L
7929,ufc 2: no way out,scott morris vs. sean daugherty,submission,1,20,scott morris,sean daugherty,NaN,NaN,NaN,NaN,0,0,open weight,W,L

In [93]:
# df_results = df_results.drop(columns = 'BOUT')

In [139]:
df_results['METHOD'].unique()

array(["tko - doctor's stoppage", 'ko/tko', 'decision - split',
       'decision - unanimous', 'submission', 'could not continue',
       'decision - majority', 'dq', 'overturned', 'other'], dtype=object)

In [140]:
method_mapping_numeric = {
    "ko/tko": 0,
    "tko - doctor's stoppage": 0,
    "submission": 1,
    "decision - unanimous": 2,
    "decision - split": 2,
    "decision - majority": 2,
    "could not continue": 0,
    "dq": 3,
    "overturned": 4,
    "other": 4
}

In [141]:
result_mapping_numeric = { 'W': 1, 'L':0,'NC':3,'D':4}

In [142]:
df_results['method_label'] = df_results['METHOD'].map(method_mapping_numeric)

In [143]:
df_results['fighter_1_result'] = df_results['fighter_1_result'].map(result_mapping_numeric)
df_results['fighter_2_result'] = df_results['fighter_2_result'].map(result_mapping_numeric)

In [145]:
df_results = df_results.drop(columns = ['METHOD'])

KeyError: "['METHOD'] not found in axis"

In [147]:
df_results['weight_class'].unique()

array(['welterweight', 'featherweight', 'flyweight', 'light heavyweight',
       'bantamweight', 'lightweight', 'strawweight', 'heavyweight',
       'catch weight', 'middleweight', 'open weight', nan], dtype=object)

In [148]:
df_results['weight_class'] = df_results['weight_class'].fillna('open weight')

In [149]:
weightclass_mapping = {'strawweight': 0,'flyweight': 1,'bantamweight': 2,'featherweight': 3,'lightweight': 4,'welterweight': 5,
                       'middleweight': 6, 'light heavyweight': 7, 'heavyweight': 8, 'catch weight': 9, 'open weight': 10}

In [150]:
df_results['weightclass_numeric'] = df_results['weight_class'].map(weightclass_mapping)

In [151]:
df_results

,EVENT,BOUT,ROUND,TIME,FIGHTER_1,FIGHTER_2,Total_Rounds_Format,Main_round_time_Format,Num_overtime_rounds_Format,Overtime_round_time_Format,gender,is_title_bout,weight_class,fighter_1_result,fighter_2_result,method_label,weightclass_numeric
0,ufc fight night: covington vs. buckley,colby covington vs. joaquin buckley,3,282,colby covington,joaquin buckley,5.0,5.0,0.0,0.0,0,0,welterweight,0,1,0,5
1,ufc fight night: covington vs. buckley,cub swanson vs. billy quarantillo,3,96,cub swanson,billy quarantillo,3.0,5.0,0.0,0.0,0,0,featherweight,1,0,0,3
2,ufc fight night: covington vs. buckley,manel kape vs. bruno silva,3,117,manel kape,bruno silva,3.0,5.0,0.0,0.0,0,0,flyweight,1,0,0,1
3,ufc fight night: covington vs. buckley,vitor petrino vs. dustin jacoby,3,224,vitor petrino,dustin jacoby,3.0,5.0,0.0,0.0,0,0,light heavyweight,0,1,0,7
4,ufc fight night: covington vs. buckley,adrian yanez vs. daniel marcos,3,300,adrian yanez,daniel marcos,3.0,5.0,0.0,0.0,0,0,bantamweight,0,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7925,ufc 2: no way out,orlando wiet vs. robert lucarelli,1,170,orlando wiet,robert lucarelli,NaN,NaN,NaN,NaN,0,0,open weight,1,0,0,10
7926,ufc 2: no way out,frank hamaker vs. thaddeus luster,1,292,frank hamaker,thaddeus luster,NaN,NaN,NaN,NaN,0,0,open weight,1,0,1,10
7927,ufc 2: no way out,johnny rhodes vs. david levicki,1,733,johnny rhodes,david levicki,NaN,NaN,NaN,NaN,0,0,open weight,1,0,0,10
7928,ufc 2: no way out,patrick smith vs. ray wizard,1,58,patrick smith,ray wizard,NaN,NaN,NaN,NaN,0,0,open weight,1,0,1,10
7929,ufc 2: no way out,scott morris vs. sean daugherty,1,20,scott morris,sean daugherty,NaN,NaN,NaN,NaN,0,0,open weight,1,0,1,10

In [152]:
df_results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7930 entries, 0 to 7929
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   EVENT                       7930 non-null   object
 1   BOUT                        7930 non-null   object
 2   ROUND                       7930 non-null   int64
 3   TIME                        7930 non-null   int64
 4   FIGHTER_1                   7930 non-null   object
 5   FIGHTER_2                   7930 non-null   object
 6   Total_Rounds_Format         7899 non-null   float64
 7   Main_round_time_Format      7899 non-null   float64
 8   Num_overtime_rounds_Format  7768 non-null   float64
 9   Overtime_round_time_Format  7899 non-null   float64
 10  gender                      7930 non-null   int64
 11  is_title_bout               7930 non-null   int64
 12  weight_class                7930 non-null   object
 13  fighter_1_result            7930 non-null   int64
 14  fighter_2_result            7930 non-null   int64
 15  method_label                7930 non-null   int64
 16  weightclass_numeric         7930 non-null   int64
dtypes: float64(4), int64(8), object(5)
memory usage: 1.0+ MB

In [153]:
df_results.to_csv('ufc_fight_results_processed_official.csv', index=False)

## df stats

In [129]:
df_stats.columns

Index(['EVENT', 'BOUT', 'ROUND', 'FIGHTER', 'KD', 'SIG.STR. %', 'TD %',
       'SUB.ATT', 'REV.', 'CTRL', 'sig_str_attempt', 'sig_str_land',
       'total_str_attempt', 'total_str_land', 'touchdown_attempt',
       'takedown_land', 'total_leg_attempt', 'total_leg_land',
       'total_distance_strike_attempt', 'total_distance_strike_land',
       'total_body_attempt', 'total_body_land', 'total_clinch_attempt',
       'total_clinch_land', 'total_ground_attempt', 'total_ground_land',
       'total_head_attempt', 'total_head_land', 'weight_class', 'gender',
       'is_title_bout', 'DATE', 'LOCATION'],
      dtype='object')

### df fighters

In [110]:
df_fighters = pd.read_csv('fighters.csv')

In [111]:
df_fighters.iloc[:5,  5:]

,Submissions,First_Round_Finishes,Striking_Accuracy,Takedown_Accuracy,Sig_Str_Landed Total,Sig_Str_Attempted Total,Takedowns_Landed_Total,Takedowns_Attempted_Total,Sig_Strikes_Per Min,Takedown_Avg_Per Min,...,Sig_Strikes_While_Clinched,Sig_Strikes_While_Grounded,Sig_Strikes_Head,Sig_Strikes_Body,Sig_Strikes_Leg,Win_by_KO/TKO,Win_by_Decision,Win_by_Submission,Place_of_Birth,Octagon_Debut
0,0,0,38%,NaN,59,155,0.0,0,3.29,0.0,...,14(24%),3(5%),51(86%),8(14%),0(0%),0(0%),0(0%),0(0%),"Orlando, United States","Jun. 24, 2006"
1,0,0,20%,0%,45,225,NaN,2,3.00,0.0,...,0(0%),0(0%),26(58%),8(18%),11(24%),0(0%),0(0%),0(0%),Kazakhstan,"Feb. 11, 2025"
2,0,0,39%,NaN,12,31,0.0,0,2.41,0.0,...,7(58%),1(8%),12(100%),0(0%),0(0%),0(0%),0(0%),0(0%),"Huntington Beach, United States","Jul. 14, 1995"
3,0,4,52%,80%,102,197,3.0,5,3.40,2.0,...,2(2%),30(29%),76(75%),8(8%),18(18%),5(100%),0(0%),0(0%),Egypt,"Jul. 30, 2022"
4,1,6,55%,NaN,77,141,0.0,0,6.61,0.0,...,2(3%),47(61%),74(96%),2(3%),1(1%),6(86%),0(0%),1(14%),"Pittsburgh, United States","Nov. 9, 2024"

In [112]:
df_fighters[['Wins', 'Losses', 'Draws']] = df_fighters['Record'].str.extract(r'(\d+)-(\d+)-(\d+)').astype(float)
df_fighters = df_fighters.drop(columns=['Record'])

In [113]:
percentage_columns = ['Striking_Accuracy', 'Takedown_Accuracy','Sig_Str_Def','Takedown_Def']
for col in percentage_columns:
    df_fighters[col] = df_fighters[col].str.rstrip('%').astype(float)/100

In [114]:
strike_columns = [
    'Sig_Str_Landed Total', 'Sig_Strikes_While_Clinched','Sig_Strikes_While_Standing',
    'Sig_Strikes_While_Grounded', 'Sig_Strikes_Head',
    'Sig_Strikes_Body', 'Sig_Strikes_Leg',
    'Win_by_KO/TKO', 'Win_by_Decision', 'Win_by_Submission'
]
for col in strike_columns:
    if df_fighters[col].dtype == 'object':
        df_fighters[[col + '_Total', col + '_Percent']] = df_fighters[col].str.extract(r'(\d+)\((\d+)%\)').astype(float)
        df_fighters[col + '_Percent'] = df_fighters[col + '_Percent'].fillna(0) 
        df_fighters[col + '_Percent'] = df_fighters[col + '_Percent'] / 100
    else:
        df_fighters[col + '_Total'] = df_fighters[col] 
        df_fighters[col + '_Percent'] = 0

In [115]:
df_fighters = df_fighters.drop(columns=[col for col in strike_columns if col in df_fighters.columns])

In [116]:
def cv_time(time):
    if isinstance(time, str):
        parts = time.split(':')
        if len(parts) == 2:
            minutes, seconds = parts
            if minutes.isdigit() and seconds.isdigit():
                return int(minutes) * 60 + int(seconds)
    return 0
df_fighters['Avg_Fight_Time'] = df_fighters['Avg_Fight_Time'].apply(cv_time)

In [143]:
df_fighters[df_fighters['Sig_Str_Def'].isna()].iloc[:10,8:]

,Sig_Str_Attempted Total,Takedowns_Landed_Total,Takedowns_Attempted_Total,Sig_Strikes_Per Min,Takedown_Avg_Per Min,Sig_Str_Def,Knockdown_Avg,Sig_Strikes_Absorbed_Per_Min,Sub_Avg_Per_Min,Takedown_Def,...,Sig_Strikes_Body_Total,Sig_Strikes_Body_Percent,Sig_Strikes_Leg_Total,Sig_Strikes_Leg_Percent,Win_by_KO/TKO_Total,Win_by_KO/TKO_Percent,Win_by_Decision_Total,Win_by_Decision_Percent,Win_by_Submission_Total,Win_by_Submission_Percent
13,0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
59,0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61,0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100,0,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [118]:
df_fighters['Takedowns_Landed_Total'] = df_fighters['Takedowns_Landed_Total'].fillna('0').astype(float)

In [126]:
df_fighters['Weight_Class'] = df_fighters['Weight_Class'].fillna('0')

In [129]:
df_fighters['Striking_Accuracy'] = df_fighters['Striking_Accuracy'].fillna('0').astype(float)
df_fighters['Takedown_Accuracy'] = df_fighters['Takedown_Accuracy'].fillna('0').astype(float)
df_fighters['Sig_Strikes_Per Min'] = df_fighters['Sig_Strikes_Per Min'].fillna('0').astype(float)
df_fighters['Takedown_Avg_Per Min'] = df_fighters['Takedown_Avg_Per Min'].fillna('0').astype(float)
df_fighters['Takedown_Avg_Per Min'] = df_fighters['Takedown_Avg_Per Min'].fillna('0').astype(float)
df_fighters['Sig_Str_Def'] = df_fighters['Sig_Str_Def'].fillna('0').astype(float)

In [147]:
columns_to_fill = [
    'Knockdown_Avg',
    'Sig_Strikes_Absorbed_Per_Min',
    'Sub_Avg_Per_Min',
    'Takedown_Def',
    'Wins',
    'Losses',
    'Draws',
    'Sig_Strikes_While_Clinched_Total',
    'Sig_Strikes_While_Standing_Total',
    'Sig_Strikes_While_Grounded_Total',
    'Sig_Strikes_Head_Total',
    'Sig_Strikes_Body_Total',
    'Sig_Strikes_Leg_Total',
]

In [148]:
for col in columns_to_fill:
    df_fighters[col] = df_fighters[col].fillna('0').astype(float)

In [149]:
df_fighters.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3015 entries, 0 to 3014
Data columns (total 44 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Name                                3015 non-null   object
 1   Nickname                            1786 non-null   object
 2   Weight_Class                        3015 non-null   object
 3   Knockouts                           3015 non-null   int64
 4   Submissions                         3015 non-null   int64
 5   First_Round_Finishes                3015 non-null   int64
 6   Striking_Accuracy                   3015 non-null   float64
 7   Takedown_Accuracy                   3015 non-null   float64
 8   Sig_Str_Attempted Total             3015 non-null   int64
 9   Takedowns_Landed_Total              3015 non-null   float64
 10  Takedowns_Attempted_Total           3015 non-null   int64
 11  Sig_Strikes_Per Min                 3015 non-null   float64
 12  Takedown_Avg_Per Min                3015 non-null   float64
 13  Sig_Str_Def                         3015 non-null   float64
 14  Knockdown_Avg                       3015 non-null   float64
 15  Sig_Strikes_Absorbed_Per_Min        3015 non-null   float64
 16  Sub_Avg_Per_Min                     3015 non-null   float64
 17  Takedown_Def                        3015 non-null   float64
 18  Avg_Fight_Time                      3015 non-null   int64
 19  Place_of_Birth                      2830 non-null   object
 20  Octagon_Debut                       3015 non-null   object
 21  Wins                                3015 non-null   float64
 22  Losses                              3015 non-null   float64
 23  Draws                               3015 non-null   float64
 24  Sig_Str_Landed Total_Total          3015 non-null   int64
 25  Sig_Str_Landed Total_Percent        3015 non-null   int64
 26  Sig_Strikes_While_Clinched_Total    3015 non-null   float64
 27  Sig_Strikes_While_Clinched_Percent  3015 non-null   float64
 28  Sig_Strikes_While_Standing_Total    3015 non-null   float64
 29  Sig_Strikes_While_Standing_Percent  3015 non-null   float64
 30  Sig_Strikes_While_Grounded_Total    3015 non-null   float64
 31  Sig_Strikes_While_Grounded_Percent  3015 non-null   float64
 32  Sig_Strikes_Head_Total              3015 non-null   float64
 33  Sig_Strikes_Head_Percent            3015 non-null   float64
 34  Sig_Strikes_Body_Total              3015 non-null   float64
 35  Sig_Strikes_Body_Percent            3015 non-null   float64
 36  Sig_Strikes_Leg_Total               3015 non-null   float64
 37  Sig_Strikes_Leg_Percent             3015 non-null   float64
 38  Win_by_KO/TKO_Total                 3015 non-null   float64
 39  Win_by_KO/TKO_Percent               3015 non-null   float64
 40  Win_by_Decision_Total               3015 non-null   float64
 41  Win_by_Decision_Percent             3015 non-null   float64
 42  Win_by_Submission_Total             3015 non-null   float64
 43  Win_by_Submission_Percent           3015 non-null   float64
dtypes: float64(31), int64(8), object(5)
memory usage: 1.0+ MB

In [150]:
df_fighters.to_csv('fighters_processed.csv', index=False)